spring:
  datasource:
    url: jdbc:h2:file:./data/treecore
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  application:
    name: treecore-library
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

server:
  servlet:
    context-path: /

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    com.treecore: debug 